import Link from "next/link";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Grid, GridItem } from "@chakra-ui/react";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Debugging</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to the world of Debugging!</h1>

        <p className={styles.description}>
          Topical articles and videos on the subject
        </p>

        {/* <Grid
          h="400px"
          templateRows="repeat(6, 1fr)"
          templateColumns="repeat(8, 1fr)"
          gap={2}
        >
          <GridItem rowSpan={5} rowStart={2} colSpan={1} bg="#61b0b7" />
          <GridItem colSpan={8} bg="#1655" />

          <GridItem colSpan={7} rowStart={2} rowSpan={5} bg="#219ebc" />
        </Grid> */}

        <div className={styles.grid}>
          <a
            href="https://javascript.info/debugging-chrome"
            className={styles.card}
          >
            <h2>Debugging in Chrome &rarr;</h2>
            <p>
              Find in-depth information about using the debugger tool in the
              browser
            </p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
